/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.tdq.common.model;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class TdqAvroMetric extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4315761177038461524L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TdqAvroMetric\",\"namespace\":\"com.ebay.tdq.common.model\",\"fields\":[{\"name\":\"metricId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"metric key\"},{\"name\":\"metricName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"metric key\"},{\"name\":\"eventTime\",\"type\":\"long\",\"doc\":\"event time\"},{\"name\":\"processTime\",\"type\":\"long\",\"doc\":\"process time\"},{\"name\":\"tags\",\"type\":[\"null\",{\"type\":\"map\",\"values\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"avro.java.string\":\"String\"}]},{\"name\":\"values\",\"type\":{\"type\":\"map\",\"values\":\"double\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TdqAvroMetric> ENCODER =
      new BinaryMessageEncoder<TdqAvroMetric>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TdqAvroMetric> DECODER =
      new BinaryMessageDecoder<TdqAvroMetric>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<TdqAvroMetric> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<TdqAvroMetric> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<TdqAvroMetric>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this TdqAvroMetric to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a TdqAvroMetric from a ByteBuffer. */
  public static TdqAvroMetric fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** metric key */
  @Deprecated public java.lang.String metricId;
  /** metric key */
  @Deprecated public java.lang.String metricName;
  /** event time */
  @Deprecated public long eventTime;
  /** process time */
  @Deprecated public long processTime;
  @Deprecated public java.util.Map<java.lang.String,java.lang.String> tags;
  @Deprecated public java.util.Map<java.lang.String,java.lang.Double> values;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TdqAvroMetric() {}

  /**
   * All-args constructor.
   * @param metricId metric key
   * @param metricName metric key
   * @param eventTime event time
   * @param processTime process time
   * @param tags The new value for tags
   * @param values The new value for values
   */
  public TdqAvroMetric(java.lang.String metricId, java.lang.String metricName, java.lang.Long eventTime, java.lang.Long processTime, java.util.Map<java.lang.String,java.lang.String> tags, java.util.Map<java.lang.String,java.lang.Double> values) {
    this.metricId = metricId;
    this.metricName = metricName;
    this.eventTime = eventTime;
    this.processTime = processTime;
    this.tags = tags;
    this.values = values;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return metricId;
    case 1: return metricName;
    case 2: return eventTime;
    case 3: return processTime;
    case 4: return tags;
    case 5: return values;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: metricId = (java.lang.String)value$; break;
    case 1: metricName = (java.lang.String)value$; break;
    case 2: eventTime = (java.lang.Long)value$; break;
    case 3: processTime = (java.lang.Long)value$; break;
    case 4: tags = (java.util.Map<java.lang.String,java.lang.String>)value$; break;
    case 5: values = (java.util.Map<java.lang.String,java.lang.Double>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'metricId' field.
   * @return metric key
   */
  public java.lang.String getMetricId() {
    return metricId;
  }

  /**
   * Sets the value of the 'metricId' field.
   * metric key
   * @param value the value to set.
   */
  public void setMetricId(java.lang.String value) {
    this.metricId = value;
  }

  /**
   * Gets the value of the 'metricName' field.
   * @return metric key
   */
  public java.lang.String getMetricName() {
    return metricName;
  }

  /**
   * Sets the value of the 'metricName' field.
   * metric key
   * @param value the value to set.
   */
  public void setMetricName(java.lang.String value) {
    this.metricName = value;
  }

  /**
   * Gets the value of the 'eventTime' field.
   * @return event time
   */
  public java.lang.Long getEventTime() {
    return eventTime;
  }

  /**
   * Sets the value of the 'eventTime' field.
   * event time
   * @param value the value to set.
   */
  public void setEventTime(java.lang.Long value) {
    this.eventTime = value;
  }

  /**
   * Gets the value of the 'processTime' field.
   * @return process time
   */
  public java.lang.Long getProcessTime() {
    return processTime;
  }

  /**
   * Sets the value of the 'processTime' field.
   * process time
   * @param value the value to set.
   */
  public void setProcessTime(java.lang.Long value) {
    this.processTime = value;
  }

  /**
   * Gets the value of the 'tags' field.
   * @return The value of the 'tags' field.
   */
  public java.util.Map<java.lang.String,java.lang.String> getTags() {
    return tags;
  }

  /**
   * Sets the value of the 'tags' field.
   * @param value the value to set.
   */
  public void setTags(java.util.Map<java.lang.String,java.lang.String> value) {
    this.tags = value;
  }

  /**
   * Gets the value of the 'values' field.
   * @return The value of the 'values' field.
   */
  public java.util.Map<java.lang.String,java.lang.Double> getValues() {
    return values;
  }

  /**
   * Sets the value of the 'values' field.
   * @param value the value to set.
   */
  public void setValues(java.util.Map<java.lang.String,java.lang.Double> value) {
    this.values = value;
  }

  /**
   * Creates a new TdqAvroMetric RecordBuilder.
   * @return A new TdqAvroMetric RecordBuilder
   */
  public static com.ebay.tdq.common.model.TdqAvroMetric.Builder newBuilder() {
    return new com.ebay.tdq.common.model.TdqAvroMetric.Builder();
  }

  /**
   * Creates a new TdqAvroMetric RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TdqAvroMetric RecordBuilder
   */
  public static com.ebay.tdq.common.model.TdqAvroMetric.Builder newBuilder(com.ebay.tdq.common.model.TdqAvroMetric.Builder other) {
    return new com.ebay.tdq.common.model.TdqAvroMetric.Builder(other);
  }

  /**
   * Creates a new TdqAvroMetric RecordBuilder by copying an existing TdqAvroMetric instance.
   * @param other The existing instance to copy.
   * @return A new TdqAvroMetric RecordBuilder
   */
  public static com.ebay.tdq.common.model.TdqAvroMetric.Builder newBuilder(com.ebay.tdq.common.model.TdqAvroMetric other) {
    return new com.ebay.tdq.common.model.TdqAvroMetric.Builder(other);
  }

  /**
   * RecordBuilder for TdqAvroMetric instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TdqAvroMetric>
    implements org.apache.avro.data.RecordBuilder<TdqAvroMetric> {

    /** metric key */
    private java.lang.String metricId;
    /** metric key */
    private java.lang.String metricName;
    /** event time */
    private long eventTime;
    /** process time */
    private long processTime;
    private java.util.Map<java.lang.String,java.lang.String> tags;
    private java.util.Map<java.lang.String,java.lang.Double> values;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.tdq.common.model.TdqAvroMetric.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.metricId)) {
        this.metricId = data().deepCopy(fields()[0].schema(), other.metricId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.metricName)) {
        this.metricName = data().deepCopy(fields()[1].schema(), other.metricName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[2].schema(), other.eventTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processTime)) {
        this.processTime = data().deepCopy(fields()[3].schema(), other.processTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tags)) {
        this.tags = data().deepCopy(fields()[4].schema(), other.tags);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.values)) {
        this.values = data().deepCopy(fields()[5].schema(), other.values);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing TdqAvroMetric instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.tdq.common.model.TdqAvroMetric other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.metricId)) {
        this.metricId = data().deepCopy(fields()[0].schema(), other.metricId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.metricName)) {
        this.metricName = data().deepCopy(fields()[1].schema(), other.metricName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.eventTime)) {
        this.eventTime = data().deepCopy(fields()[2].schema(), other.eventTime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.processTime)) {
        this.processTime = data().deepCopy(fields()[3].schema(), other.processTime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.tags)) {
        this.tags = data().deepCopy(fields()[4].schema(), other.tags);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.values)) {
        this.values = data().deepCopy(fields()[5].schema(), other.values);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'metricId' field.
      * metric key
      * @return The value.
      */
    public java.lang.String getMetricId() {
      return metricId;
    }

    /**
      * Sets the value of the 'metricId' field.
      * metric key
      * @param value The value of 'metricId'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setMetricId(java.lang.String value) {
      validate(fields()[0], value);
      this.metricId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'metricId' field has been set.
      * metric key
      * @return True if the 'metricId' field has been set, false otherwise.
      */
    public boolean hasMetricId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'metricId' field.
      * metric key
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearMetricId() {
      metricId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'metricName' field.
      * metric key
      * @return The value.
      */
    public java.lang.String getMetricName() {
      return metricName;
    }

    /**
      * Sets the value of the 'metricName' field.
      * metric key
      * @param value The value of 'metricName'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setMetricName(java.lang.String value) {
      validate(fields()[1], value);
      this.metricName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'metricName' field has been set.
      * metric key
      * @return True if the 'metricName' field has been set, false otherwise.
      */
    public boolean hasMetricName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'metricName' field.
      * metric key
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearMetricName() {
      metricName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'eventTime' field.
      * event time
      * @return The value.
      */
    public java.lang.Long getEventTime() {
      return eventTime;
    }

    /**
      * Sets the value of the 'eventTime' field.
      * event time
      * @param value The value of 'eventTime'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setEventTime(long value) {
      validate(fields()[2], value);
      this.eventTime = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'eventTime' field has been set.
      * event time
      * @return True if the 'eventTime' field has been set, false otherwise.
      */
    public boolean hasEventTime() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'eventTime' field.
      * event time
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearEventTime() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'processTime' field.
      * process time
      * @return The value.
      */
    public java.lang.Long getProcessTime() {
      return processTime;
    }

    /**
      * Sets the value of the 'processTime' field.
      * process time
      * @param value The value of 'processTime'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setProcessTime(long value) {
      validate(fields()[3], value);
      this.processTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'processTime' field has been set.
      * process time
      * @return True if the 'processTime' field has been set, false otherwise.
      */
    public boolean hasProcessTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'processTime' field.
      * process time
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearProcessTime() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'tags' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.String> getTags() {
      return tags;
    }

    /**
      * Sets the value of the 'tags' field.
      * @param value The value of 'tags'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setTags(java.util.Map<java.lang.String,java.lang.String> value) {
      validate(fields()[4], value);
      this.tags = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'tags' field has been set.
      * @return True if the 'tags' field has been set, false otherwise.
      */
    public boolean hasTags() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'tags' field.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearTags() {
      tags = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'values' field.
      * @return The value.
      */
    public java.util.Map<java.lang.String,java.lang.Double> getValues() {
      return values;
    }

    /**
      * Sets the value of the 'values' field.
      * @param value The value of 'values'.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder setValues(java.util.Map<java.lang.String,java.lang.Double> value) {
      validate(fields()[5], value);
      this.values = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'values' field has been set.
      * @return True if the 'values' field has been set, false otherwise.
      */
    public boolean hasValues() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'values' field.
      * @return This builder.
      */
    public com.ebay.tdq.common.model.TdqAvroMetric.Builder clearValues() {
      values = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TdqAvroMetric build() {
      try {
        TdqAvroMetric record = new TdqAvroMetric();
        record.metricId = fieldSetFlags()[0] ? this.metricId : (java.lang.String) defaultValue(fields()[0]);
        record.metricName = fieldSetFlags()[1] ? this.metricName : (java.lang.String) defaultValue(fields()[1]);
        record.eventTime = fieldSetFlags()[2] ? this.eventTime : (java.lang.Long) defaultValue(fields()[2]);
        record.processTime = fieldSetFlags()[3] ? this.processTime : (java.lang.Long) defaultValue(fields()[3]);
        record.tags = fieldSetFlags()[4] ? this.tags : (java.util.Map<java.lang.String,java.lang.String>) defaultValue(fields()[4]);
        record.values = fieldSetFlags()[5] ? this.values : (java.util.Map<java.lang.String,java.lang.Double>) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TdqAvroMetric>
    WRITER$ = (org.apache.avro.io.DatumWriter<TdqAvroMetric>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TdqAvroMetric>
    READER$ = (org.apache.avro.io.DatumReader<TdqAvroMetric>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
