pronto:
  index-pattern: tdq-metrics-pre-prod-
  latency-index-pattern: tdq-metrics-pre-prod-latency-
  scheme: https
  hostname: estdq-datalvs.vip.ebay.com
  port: 443
  username: _TDQ_SVC_USER
  password: "@BxHqFyz+Gzeq+2D"