/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.sojourner.ubd.common.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class IntermediateSession extends org.apache.avro.specific.SpecificRecordBase implements
    org.apache.avro.specific.SpecificRecord {

  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse(
      "{\"type\":\"record\",\"name\":\"IntermediateSession\",\"namespace\":\"com.ebay.sojourner"
          + ".ubd.common.model\",\"fields\":[{\"name\":\"guid\",\"type\":[\"null\","
          + "{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"from ubisession "
          + "guid\"},{\"name\":\"guid1\",\"type\":[\"null\",\"long\"],\"doc\":\"from ubisession "
          + "guid1\"},{\"name\":\"guid2\",\"type\":[\"null\",\"long\"],\"doc\":\"from ubisession "
          + "guid2\"},{\"name\":\"absEventCnt\",\"type\":[\"null\",\"int\"],\"doc\":\"from "
          + "ubisession absEventCnt\"},{\"name\":\"nonIframeRdtEventCnt\",\"type\":[\"null\","
          + "\"int\"],\"doc\":\"from ubisession nonIframeRdtEventCnt\"},{\"name\":\"ip\","
          + "\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],"
          + "\"doc\":\"from ubisession ip\"},{\"name\":\"userAgent\",\"type\":[\"null\","
          + "{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"from ubisession "
          + "userAgent\"},{\"name\":\"singleClickSessionFlag\",\"type\":[\"null\",\"boolean\"],"
          + "\"doc\":\"from ubisession singleClickSessionFlag\"},{\"name\":\"botFlag\","
          + "\"type\":[\"null\",\"int\"],\"doc\":\"from ubisession botFlag\"},"
          + "{\"name\":\"firstCguid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java"
          + ".string\":\"String\"}],\"doc\":\"from ubisession firstCguid\"},"
          + "{\"name\":\"firstUserId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java"
          + ".string\":\"String\"}],\"doc\":\"from ubisession firstUserId\"},"
          + "{\"name\":\"validPageCnt\",\"type\":[\"null\",\"int\"],\"doc\":\"from ubisession "
          + "validPageCnt\"},{\"name\":\"trafficSrcId\",\"type\":[\"null\",\"int\"],"
          + "\"doc\":\"from ubisession trafficSrcId\"},{\"name\":\"exInternalIp\","
          + "\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],"
          + "\"doc\":\"from ubisession exInternalIp\"},{\"name\":\"homepageCnt\","
          + "\"type\":[\"null\",\"int\"],\"doc\":\"from ubisession homepageCnt\"},"
          + "{\"name\":\"signinPageCnt\",\"type\":[\"null\",\"int\"],\"doc\":\"fron ubisession "
          + "signinPageCnt\"},{\"name\":\"cobrand\",\"type\":[\"null\",\"int\"],\"doc\":\"from "
          + "ubisession cobrand\"},{\"name\":\"startTimestamp\",\"type\":[\"null\",\"long\"],"
          + "\"doc\":\"from ubisession startTimestamp\"},{\"name\":\"endTimestamp\","
          + "\"type\":[\"null\",\"long\"],\"doc\":\"from ubisession endTimestamp\"},"
          + "{\"name\":\"agentCnt\",\"type\":[\"null\",\"int\"],\"doc\":\"from ubisession "
          + "agentCnt\"},{\"name\":\"firstAppId\",\"type\":[\"null\",\"int\"],\"doc\":\"from "
          + "ubisession firstAppId\"},{\"name\":\"bidBinConfirmFlag\",\"type\":[\"null\","
          + "\"boolean\"],\"doc\":\"from ubisession bidBinConfirmFlag\"},{\"name\":\"clientIp\","
          + "\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],"
          + "\"doc\":\"from ubisession clientIp\"},{\"name\":\"absStartTimestamp\","
          + "\"type\":[\"null\",\"long\"],\"doc\":\"from ubisession absStartTimestamp\"},"
          + "{\"name\":\"absEndTimestamp\",\"type\":[\"null\",\"long\"],\"doc\":\"from ubisession"
          + " absEndTimestamp\"},{\"name\":\"familyViCnt\",\"type\":[\"null\",\"int\"],"
          + "\"doc\":\"from ubisession familyViCnt\"},{\"name\":\"agentString\","
          + "\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],"
          + "\"doc\":\"from ubisession agentString\"},{\"name\":\"botFlagList\","
          + "\"type\":[\"null\",{\"type\":\"array\",\"items\":\"int\"}],\"default\":null}]}");
  private static final long serialVersionUID = -2351548218430267511L;
  private static SpecificData MODEL$ = new SpecificData();
  private static final BinaryMessageEncoder<IntermediateSession> ENCODER =
      new BinaryMessageEncoder<IntermediateSession>(MODEL$, SCHEMA$);
  private static final BinaryMessageDecoder<IntermediateSession> DECODER =
      new BinaryMessageDecoder<IntermediateSession>(MODEL$, SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<IntermediateSession>
      WRITER$ = (org.apache.avro.io.DatumWriter<IntermediateSession>) MODEL$
      .createDatumWriter(SCHEMA$);
  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<IntermediateSession>
      READER$ = (org.apache.avro.io.DatumReader<IntermediateSession>) MODEL$
      .createDatumReader(SCHEMA$);
  /**
   * from ubisession guid
   */
  @Deprecated
  public java.lang.String guid;
  /**
   * from ubisession guid1
   */
  @Deprecated
  public java.lang.Long guid1;
  /**
   * from ubisession guid2
   */
  @Deprecated
  public java.lang.Long guid2;
  /**
   * from ubisession absEventCnt
   */
  @Deprecated
  public java.lang.Integer absEventCnt;
  /**
   * from ubisession nonIframeRdtEventCnt
   */
  @Deprecated
  public java.lang.Integer nonIframeRdtEventCnt;
  /**
   * from ubisession ip
   */
  @Deprecated
  public java.lang.String ip;
  /**
   * from ubisession userAgent
   */
  @Deprecated
  public java.lang.String userAgent;
  /**
   * from ubisession singleClickSessionFlag
   */
  @Deprecated
  public java.lang.Boolean singleClickSessionFlag;
  /**
   * from ubisession botFlag
   */
  @Deprecated
  public java.lang.Integer botFlag;
  /**
   * from ubisession firstCguid
   */
  @Deprecated
  public java.lang.String firstCguid;
  /**
   * from ubisession firstUserId
   */
  @Deprecated
  public java.lang.String firstUserId;
  /**
   * from ubisession validPageCnt
   */
  @Deprecated
  public java.lang.Integer validPageCnt;
  /**
   * from ubisession trafficSrcId
   */
  @Deprecated
  public java.lang.Integer trafficSrcId;
  /**
   * from ubisession exInternalIp
   */
  @Deprecated
  public java.lang.String exInternalIp;
  /**
   * from ubisession homepageCnt
   */
  @Deprecated
  public java.lang.Integer homepageCnt;
  /**
   * fron ubisession signinPageCnt
   */
  @Deprecated
  public java.lang.Integer signinPageCnt;
  /**
   * from ubisession cobrand
   */
  @Deprecated
  public java.lang.Integer cobrand;
  /**
   * from ubisession startTimestamp
   */
  @Deprecated
  public java.lang.Long startTimestamp;
  /**
   * from ubisession endTimestamp
   */
  @Deprecated
  public java.lang.Long endTimestamp;
  /**
   * from ubisession agentCnt
   */
  @Deprecated
  public java.lang.Integer agentCnt;
  /**
   * from ubisession firstAppId
   */
  @Deprecated
  public java.lang.Integer firstAppId;
  /**
   * from ubisession bidBinConfirmFlag
   */
  @Deprecated
  public java.lang.Boolean bidBinConfirmFlag;
  /**
   * from ubisession clientIp
   */
  @Deprecated
  public java.lang.String clientIp;
  /**
   * from ubisession absStartTimestamp
   */
  @Deprecated
  public java.lang.Long absStartTimestamp;
  /**
   * from ubisession absEndTimestamp
   */
  @Deprecated
  public java.lang.Long absEndTimestamp;
  /**
   * from ubisession familyViCnt
   */
  @Deprecated
  public java.lang.Integer familyViCnt;
  /**
   * from ubisession agentString
   */
  @Deprecated
  public java.lang.String agentString;
  @Deprecated
  public java.util.List<java.lang.Integer> botFlagList;

  /**
   * Default constructor.  Note that this does not initialize fields to their default values from
   * the schema.  If that is desired then one should use <code>newBuilder()</code>.
   */
  public IntermediateSession() {
  }

  /**
   * All-args constructor.
   *
   * @param guid from ubisession guid
   * @param guid1 from ubisession guid1
   * @param guid2 from ubisession guid2
   * @param absEventCnt from ubisession absEventCnt
   * @param nonIframeRdtEventCnt from ubisession nonIframeRdtEventCnt
   * @param ip from ubisession ip
   * @param userAgent from ubisession userAgent
   * @param singleClickSessionFlag from ubisession singleClickSessionFlag
   * @param botFlag from ubisession botFlag
   * @param firstCguid from ubisession firstCguid
   * @param firstUserId from ubisession firstUserId
   * @param validPageCnt from ubisession validPageCnt
   * @param trafficSrcId from ubisession trafficSrcId
   * @param exInternalIp from ubisession exInternalIp
   * @param homepageCnt from ubisession homepageCnt
   * @param signinPageCnt fron ubisession signinPageCnt
   * @param cobrand from ubisession cobrand
   * @param startTimestamp from ubisession startTimestamp
   * @param endTimestamp from ubisession endTimestamp
   * @param agentCnt from ubisession agentCnt
   * @param firstAppId from ubisession firstAppId
   * @param bidBinConfirmFlag from ubisession bidBinConfirmFlag
   * @param clientIp from ubisession clientIp
   * @param absStartTimestamp from ubisession absStartTimestamp
   * @param absEndTimestamp from ubisession absEndTimestamp
   * @param familyViCnt from ubisession familyViCnt
   * @param agentString from ubisession agentString
   * @param botFlagList The new value for botFlagList
   */
  public IntermediateSession(java.lang.String guid, java.lang.Long guid1, java.lang.Long guid2,
      java.lang.Integer absEventCnt, java.lang.Integer nonIframeRdtEventCnt, java.lang.String ip,
      java.lang.String userAgent, java.lang.Boolean singleClickSessionFlag,
      java.lang.Integer botFlag, java.lang.String firstCguid, java.lang.String firstUserId,
      java.lang.Integer validPageCnt, java.lang.Integer trafficSrcId, java.lang.String exInternalIp,
      java.lang.Integer homepageCnt, java.lang.Integer signinPageCnt, java.lang.Integer cobrand,
      java.lang.Long startTimestamp, java.lang.Long endTimestamp, java.lang.Integer agentCnt,
      java.lang.Integer firstAppId, java.lang.Boolean bidBinConfirmFlag, java.lang.String clientIp,
      java.lang.Long absStartTimestamp, java.lang.Long absEndTimestamp,
      java.lang.Integer familyViCnt, java.lang.String agentString,
      java.util.List<java.lang.Integer> botFlagList) {
    this.guid = guid;
    this.guid1 = guid1;
    this.guid2 = guid2;
    this.absEventCnt = absEventCnt;
    this.nonIframeRdtEventCnt = nonIframeRdtEventCnt;
    this.ip = ip;
    this.userAgent = userAgent;
    this.singleClickSessionFlag = singleClickSessionFlag;
    this.botFlag = botFlag;
    this.firstCguid = firstCguid;
    this.firstUserId = firstUserId;
    this.validPageCnt = validPageCnt;
    this.trafficSrcId = trafficSrcId;
    this.exInternalIp = exInternalIp;
    this.homepageCnt = homepageCnt;
    this.signinPageCnt = signinPageCnt;
    this.cobrand = cobrand;
    this.startTimestamp = startTimestamp;
    this.endTimestamp = endTimestamp;
    this.agentCnt = agentCnt;
    this.firstAppId = firstAppId;
    this.bidBinConfirmFlag = bidBinConfirmFlag;
    this.clientIp = clientIp;
    this.absStartTimestamp = absStartTimestamp;
    this.absEndTimestamp = absEndTimestamp;
    this.familyViCnt = familyViCnt;
    this.agentString = agentString;
    this.botFlagList = botFlagList;
  }

  public static org.apache.avro.Schema getClassSchema() {
    return SCHEMA$;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<IntermediateSession> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
   * SchemaStore}.
   *
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<IntermediateSession> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<IntermediateSession>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Deserializes a IntermediateSession from a ByteBuffer.
   */
  public static IntermediateSession fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /**
   * Creates a new IntermediateSession RecordBuilder.
   *
   * @return A new IntermediateSession RecordBuilder
   */
  public static com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder newBuilder() {
    return new com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder();
  }

  /**
   * Creates a new IntermediateSession RecordBuilder by copying an existing Builder.
   *
   * @param other The existing builder to copy.
   * @return A new IntermediateSession RecordBuilder
   */
  public static com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder newBuilder(
      com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder other) {
    return new com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder(other);
  }

  /**
   * Creates a new IntermediateSession RecordBuilder by copying an existing IntermediateSession
   * instance.
   *
   * @param other The existing instance to copy.
   * @return A new IntermediateSession RecordBuilder
   */
  public static com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder newBuilder(
      com.ebay.sojourner.ubd.common.model.IntermediateSession other) {
    return new com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder(other);
  }

  /**
   * Serializes this IntermediateSession to a ByteBuffer.
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  public org.apache.avro.Schema getSchema() {
    return SCHEMA$;
  }

  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0:
        return guid;
      case 1:
        return guid1;
      case 2:
        return guid2;
      case 3:
        return absEventCnt;
      case 4:
        return nonIframeRdtEventCnt;
      case 5:
        return ip;
      case 6:
        return userAgent;
      case 7:
        return singleClickSessionFlag;
      case 8:
        return botFlag;
      case 9:
        return firstCguid;
      case 10:
        return firstUserId;
      case 11:
        return validPageCnt;
      case 12:
        return trafficSrcId;
      case 13:
        return exInternalIp;
      case 14:
        return homepageCnt;
      case 15:
        return signinPageCnt;
      case 16:
        return cobrand;
      case 17:
        return startTimestamp;
      case 18:
        return endTimestamp;
      case 19:
        return agentCnt;
      case 20:
        return firstAppId;
      case 21:
        return bidBinConfirmFlag;
      case 22:
        return clientIp;
      case 23:
        return absStartTimestamp;
      case 24:
        return absEndTimestamp;
      case 25:
        return familyViCnt;
      case 26:
        return agentString;
      case 27:
        return botFlagList;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value = "unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0:
        guid = (java.lang.String) value$;
        break;
      case 1:
        guid1 = (java.lang.Long) value$;
        break;
      case 2:
        guid2 = (java.lang.Long) value$;
        break;
      case 3:
        absEventCnt = (java.lang.Integer) value$;
        break;
      case 4:
        nonIframeRdtEventCnt = (java.lang.Integer) value$;
        break;
      case 5:
        ip = (java.lang.String) value$;
        break;
      case 6:
        userAgent = (java.lang.String) value$;
        break;
      case 7:
        singleClickSessionFlag = (java.lang.Boolean) value$;
        break;
      case 8:
        botFlag = (java.lang.Integer) value$;
        break;
      case 9:
        firstCguid = (java.lang.String) value$;
        break;
      case 10:
        firstUserId = (java.lang.String) value$;
        break;
      case 11:
        validPageCnt = (java.lang.Integer) value$;
        break;
      case 12:
        trafficSrcId = (java.lang.Integer) value$;
        break;
      case 13:
        exInternalIp = (java.lang.String) value$;
        break;
      case 14:
        homepageCnt = (java.lang.Integer) value$;
        break;
      case 15:
        signinPageCnt = (java.lang.Integer) value$;
        break;
      case 16:
        cobrand = (java.lang.Integer) value$;
        break;
      case 17:
        startTimestamp = (java.lang.Long) value$;
        break;
      case 18:
        endTimestamp = (java.lang.Long) value$;
        break;
      case 19:
        agentCnt = (java.lang.Integer) value$;
        break;
      case 20:
        firstAppId = (java.lang.Integer) value$;
        break;
      case 21:
        bidBinConfirmFlag = (java.lang.Boolean) value$;
        break;
      case 22:
        clientIp = (java.lang.String) value$;
        break;
      case 23:
        absStartTimestamp = (java.lang.Long) value$;
        break;
      case 24:
        absEndTimestamp = (java.lang.Long) value$;
        break;
      case 25:
        familyViCnt = (java.lang.Integer) value$;
        break;
      case 26:
        agentString = (java.lang.String) value$;
        break;
      case 27:
        botFlagList = (java.util.List<java.lang.Integer>) value$;
        break;
      default:
        throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'guid' field.
   *
   * @return from ubisession guid
   */
  public java.lang.String getGuid() {
    return guid;
  }

  /**
   * Sets the value of the 'guid' field. from ubisession guid
   *
   * @param value the value to set.
   */
  public void setGuid(java.lang.String value) {
    this.guid = value;
  }

  /**
   * Gets the value of the 'guid1' field.
   *
   * @return from ubisession guid1
   */
  public java.lang.Long getGuid1() {
    return guid1;
  }

  /**
   * Sets the value of the 'guid1' field. from ubisession guid1
   *
   * @param value the value to set.
   */
  public void setGuid1(java.lang.Long value) {
    this.guid1 = value;
  }

  /**
   * Gets the value of the 'guid2' field.
   *
   * @return from ubisession guid2
   */
  public java.lang.Long getGuid2() {
    return guid2;
  }

  /**
   * Sets the value of the 'guid2' field. from ubisession guid2
   *
   * @param value the value to set.
   */
  public void setGuid2(java.lang.Long value) {
    this.guid2 = value;
  }

  /**
   * Gets the value of the 'absEventCnt' field.
   *
   * @return from ubisession absEventCnt
   */
  public java.lang.Integer getAbsEventCnt() {
    return absEventCnt;
  }

  /**
   * Sets the value of the 'absEventCnt' field. from ubisession absEventCnt
   *
   * @param value the value to set.
   */
  public void setAbsEventCnt(java.lang.Integer value) {
    this.absEventCnt = value;
  }

  /**
   * Gets the value of the 'nonIframeRdtEventCnt' field.
   *
   * @return from ubisession nonIframeRdtEventCnt
   */
  public java.lang.Integer getNonIframeRdtEventCnt() {
    return nonIframeRdtEventCnt;
  }

  /**
   * Sets the value of the 'nonIframeRdtEventCnt' field. from ubisession nonIframeRdtEventCnt
   *
   * @param value the value to set.
   */
  public void setNonIframeRdtEventCnt(java.lang.Integer value) {
    this.nonIframeRdtEventCnt = value;
  }

  /**
   * Gets the value of the 'ip' field.
   *
   * @return from ubisession ip
   */
  public java.lang.String getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field. from ubisession ip
   *
   * @param value the value to set.
   */
  public void setIp(java.lang.String value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'userAgent' field.
   *
   * @return from ubisession userAgent
   */
  public java.lang.String getUserAgent() {
    return userAgent;
  }

  /**
   * Sets the value of the 'userAgent' field. from ubisession userAgent
   *
   * @param value the value to set.
   */
  public void setUserAgent(java.lang.String value) {
    this.userAgent = value;
  }

  /**
   * Gets the value of the 'singleClickSessionFlag' field.
   *
   * @return from ubisession singleClickSessionFlag
   */
  public java.lang.Boolean getSingleClickSessionFlag() {
    return singleClickSessionFlag;
  }

  /**
   * Sets the value of the 'singleClickSessionFlag' field. from ubisession singleClickSessionFlag
   *
   * @param value the value to set.
   */
  public void setSingleClickSessionFlag(java.lang.Boolean value) {
    this.singleClickSessionFlag = value;
  }

  /**
   * Gets the value of the 'botFlag' field.
   *
   * @return from ubisession botFlag
   */
  public java.lang.Integer getBotFlag() {
    return botFlag;
  }

  /**
   * Sets the value of the 'botFlag' field. from ubisession botFlag
   *
   * @param value the value to set.
   */
  public void setBotFlag(java.lang.Integer value) {
    this.botFlag = value;
  }

  /**
   * Gets the value of the 'firstCguid' field.
   *
   * @return from ubisession firstCguid
   */
  public java.lang.String getFirstCguid() {
    return firstCguid;
  }

  /**
   * Sets the value of the 'firstCguid' field. from ubisession firstCguid
   *
   * @param value the value to set.
   */
  public void setFirstCguid(java.lang.String value) {
    this.firstCguid = value;
  }

  /**
   * Gets the value of the 'firstUserId' field.
   *
   * @return from ubisession firstUserId
   */
  public java.lang.String getFirstUserId() {
    return firstUserId;
  }

  /**
   * Sets the value of the 'firstUserId' field. from ubisession firstUserId
   *
   * @param value the value to set.
   */
  public void setFirstUserId(java.lang.String value) {
    this.firstUserId = value;
  }

  /**
   * Gets the value of the 'validPageCnt' field.
   *
   * @return from ubisession validPageCnt
   */
  public java.lang.Integer getValidPageCnt() {
    return validPageCnt;
  }

  /**
   * Sets the value of the 'validPageCnt' field. from ubisession validPageCnt
   *
   * @param value the value to set.
   */
  public void setValidPageCnt(java.lang.Integer value) {
    this.validPageCnt = value;
  }

  /**
   * Gets the value of the 'trafficSrcId' field.
   *
   * @return from ubisession trafficSrcId
   */
  public java.lang.Integer getTrafficSrcId() {
    return trafficSrcId;
  }

  /**
   * Sets the value of the 'trafficSrcId' field. from ubisession trafficSrcId
   *
   * @param value the value to set.
   */
  public void setTrafficSrcId(java.lang.Integer value) {
    this.trafficSrcId = value;
  }

  /**
   * Gets the value of the 'exInternalIp' field.
   *
   * @return from ubisession exInternalIp
   */
  public java.lang.String getExInternalIp() {
    return exInternalIp;
  }

  /**
   * Sets the value of the 'exInternalIp' field. from ubisession exInternalIp
   *
   * @param value the value to set.
   */
  public void setExInternalIp(java.lang.String value) {
    this.exInternalIp = value;
  }

  /**
   * Gets the value of the 'homepageCnt' field.
   *
   * @return from ubisession homepageCnt
   */
  public java.lang.Integer getHomepageCnt() {
    return homepageCnt;
  }

  /**
   * Sets the value of the 'homepageCnt' field. from ubisession homepageCnt
   *
   * @param value the value to set.
   */
  public void setHomepageCnt(java.lang.Integer value) {
    this.homepageCnt = value;
  }

  /**
   * Gets the value of the 'signinPageCnt' field.
   *
   * @return fron ubisession signinPageCnt
   */
  public java.lang.Integer getSigninPageCnt() {
    return signinPageCnt;
  }

  /**
   * Sets the value of the 'signinPageCnt' field. fron ubisession signinPageCnt
   *
   * @param value the value to set.
   */
  public void setSigninPageCnt(java.lang.Integer value) {
    this.signinPageCnt = value;
  }

  /**
   * Gets the value of the 'cobrand' field.
   *
   * @return from ubisession cobrand
   */
  public java.lang.Integer getCobrand() {
    return cobrand;
  }

  /**
   * Sets the value of the 'cobrand' field. from ubisession cobrand
   *
   * @param value the value to set.
   */
  public void setCobrand(java.lang.Integer value) {
    this.cobrand = value;
  }

  /**
   * Gets the value of the 'startTimestamp' field.
   *
   * @return from ubisession startTimestamp
   */
  public java.lang.Long getStartTimestamp() {
    return startTimestamp;
  }

  /**
   * Sets the value of the 'startTimestamp' field. from ubisession startTimestamp
   *
   * @param value the value to set.
   */
  public void setStartTimestamp(java.lang.Long value) {
    this.startTimestamp = value;
  }

  /**
   * Gets the value of the 'endTimestamp' field.
   *
   * @return from ubisession endTimestamp
   */
  public java.lang.Long getEndTimestamp() {
    return endTimestamp;
  }

  /**
   * Sets the value of the 'endTimestamp' field. from ubisession endTimestamp
   *
   * @param value the value to set.
   */
  public void setEndTimestamp(java.lang.Long value) {
    this.endTimestamp = value;
  }

  /**
   * Gets the value of the 'agentCnt' field.
   *
   * @return from ubisession agentCnt
   */
  public java.lang.Integer getAgentCnt() {
    return agentCnt;
  }

  /**
   * Sets the value of the 'agentCnt' field. from ubisession agentCnt
   *
   * @param value the value to set.
   */
  public void setAgentCnt(java.lang.Integer value) {
    this.agentCnt = value;
  }

  /**
   * Gets the value of the 'firstAppId' field.
   *
   * @return from ubisession firstAppId
   */
  public java.lang.Integer getFirstAppId() {
    return firstAppId;
  }

  /**
   * Sets the value of the 'firstAppId' field. from ubisession firstAppId
   *
   * @param value the value to set.
   */
  public void setFirstAppId(java.lang.Integer value) {
    this.firstAppId = value;
  }

  /**
   * Gets the value of the 'bidBinConfirmFlag' field.
   *
   * @return from ubisession bidBinConfirmFlag
   */
  public java.lang.Boolean getBidBinConfirmFlag() {
    return bidBinConfirmFlag;
  }

  /**
   * Sets the value of the 'bidBinConfirmFlag' field. from ubisession bidBinConfirmFlag
   *
   * @param value the value to set.
   */
  public void setBidBinConfirmFlag(java.lang.Boolean value) {
    this.bidBinConfirmFlag = value;
  }

  /**
   * Gets the value of the 'clientIp' field.
   *
   * @return from ubisession clientIp
   */
  public java.lang.String getClientIp() {
    return clientIp;
  }

  /**
   * Sets the value of the 'clientIp' field. from ubisession clientIp
   *
   * @param value the value to set.
   */
  public void setClientIp(java.lang.String value) {
    this.clientIp = value;
  }

  /**
   * Gets the value of the 'absStartTimestamp' field.
   *
   * @return from ubisession absStartTimestamp
   */
  public java.lang.Long getAbsStartTimestamp() {
    return absStartTimestamp;
  }

  /**
   * Sets the value of the 'absStartTimestamp' field. from ubisession absStartTimestamp
   *
   * @param value the value to set.
   */
  public void setAbsStartTimestamp(java.lang.Long value) {
    this.absStartTimestamp = value;
  }

  /**
   * Gets the value of the 'absEndTimestamp' field.
   *
   * @return from ubisession absEndTimestamp
   */
  public java.lang.Long getAbsEndTimestamp() {
    return absEndTimestamp;
  }

  /**
   * Sets the value of the 'absEndTimestamp' field. from ubisession absEndTimestamp
   *
   * @param value the value to set.
   */
  public void setAbsEndTimestamp(java.lang.Long value) {
    this.absEndTimestamp = value;
  }

  /**
   * Gets the value of the 'familyViCnt' field.
   *
   * @return from ubisession familyViCnt
   */
  public java.lang.Integer getFamilyViCnt() {
    return familyViCnt;
  }

  /**
   * Sets the value of the 'familyViCnt' field. from ubisession familyViCnt
   *
   * @param value the value to set.
   */
  public void setFamilyViCnt(java.lang.Integer value) {
    this.familyViCnt = value;
  }

  /**
   * Gets the value of the 'agentString' field.
   *
   * @return from ubisession agentString
   */
  public java.lang.String getAgentString() {
    return agentString;
  }

  /**
   * Sets the value of the 'agentString' field. from ubisession agentString
   *
   * @param value the value to set.
   */
  public void setAgentString(java.lang.String value) {
    this.agentString = value;
  }

  /**
   * Gets the value of the 'botFlagList' field.
   *
   * @return The value of the 'botFlagList' field.
   */
  public java.util.List<java.lang.Integer> getBotFlagList() {
    return botFlagList;
  }

  /**
   * Sets the value of the 'botFlagList' field.
   *
   * @param value the value to set.
   */
  public void setBotFlagList(java.util.List<java.lang.Integer> value) {
    this.botFlagList = value;
  }

  @Override
  public void writeExternal(java.io.ObjectOutput out)
      throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @Override
  public void readExternal(java.io.ObjectInput in)
      throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  /**
   * RecordBuilder for IntermediateSession instances.
   */
  public static class Builder extends
      org.apache.avro.specific.SpecificRecordBuilderBase<IntermediateSession>
      implements org.apache.avro.data.RecordBuilder<IntermediateSession> {

    /**
     * from ubisession guid
     */
    private java.lang.String guid;
    /**
     * from ubisession guid1
     */
    private java.lang.Long guid1;
    /**
     * from ubisession guid2
     */
    private java.lang.Long guid2;
    /**
     * from ubisession absEventCnt
     */
    private java.lang.Integer absEventCnt;
    /**
     * from ubisession nonIframeRdtEventCnt
     */
    private java.lang.Integer nonIframeRdtEventCnt;
    /**
     * from ubisession ip
     */
    private java.lang.String ip;
    /**
     * from ubisession userAgent
     */
    private java.lang.String userAgent;
    /**
     * from ubisession singleClickSessionFlag
     */
    private java.lang.Boolean singleClickSessionFlag;
    /**
     * from ubisession botFlag
     */
    private java.lang.Integer botFlag;
    /**
     * from ubisession firstCguid
     */
    private java.lang.String firstCguid;
    /**
     * from ubisession firstUserId
     */
    private java.lang.String firstUserId;
    /**
     * from ubisession validPageCnt
     */
    private java.lang.Integer validPageCnt;
    /**
     * from ubisession trafficSrcId
     */
    private java.lang.Integer trafficSrcId;
    /**
     * from ubisession exInternalIp
     */
    private java.lang.String exInternalIp;
    /**
     * from ubisession homepageCnt
     */
    private java.lang.Integer homepageCnt;
    /**
     * fron ubisession signinPageCnt
     */
    private java.lang.Integer signinPageCnt;
    /**
     * from ubisession cobrand
     */
    private java.lang.Integer cobrand;
    /**
     * from ubisession startTimestamp
     */
    private java.lang.Long startTimestamp;
    /**
     * from ubisession endTimestamp
     */
    private java.lang.Long endTimestamp;
    /**
     * from ubisession agentCnt
     */
    private java.lang.Integer agentCnt;
    /**
     * from ubisession firstAppId
     */
    private java.lang.Integer firstAppId;
    /**
     * from ubisession bidBinConfirmFlag
     */
    private java.lang.Boolean bidBinConfirmFlag;
    /**
     * from ubisession clientIp
     */
    private java.lang.String clientIp;
    /**
     * from ubisession absStartTimestamp
     */
    private java.lang.Long absStartTimestamp;
    /**
     * from ubisession absEndTimestamp
     */
    private java.lang.Long absEndTimestamp;
    /**
     * from ubisession familyViCnt
     */
    private java.lang.Integer familyViCnt;
    /**
     * from ubisession agentString
     */
    private java.lang.String agentString;
    private java.util.List<java.lang.Integer> botFlagList;

    /**
     * Creates a new Builder
     */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     *
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.guid1)) {
        this.guid1 = data().deepCopy(fields()[1].schema(), other.guid1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.guid2)) {
        this.guid2 = data().deepCopy(fields()[2].schema(), other.guid2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.absEventCnt)) {
        this.absEventCnt = data().deepCopy(fields()[3].schema(), other.absEventCnt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nonIframeRdtEventCnt)) {
        this.nonIframeRdtEventCnt = data()
            .deepCopy(fields()[4].schema(), other.nonIframeRdtEventCnt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ip)) {
        this.ip = data().deepCopy(fields()[5].schema(), other.ip);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[6].schema(), other.userAgent);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.singleClickSessionFlag)) {
        this.singleClickSessionFlag = data()
            .deepCopy(fields()[7].schema(), other.singleClickSessionFlag);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[8].schema(), other.botFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.firstCguid)) {
        this.firstCguid = data().deepCopy(fields()[9].schema(), other.firstCguid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.firstUserId)) {
        this.firstUserId = data().deepCopy(fields()[10].schema(), other.firstUserId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.validPageCnt)) {
        this.validPageCnt = data().deepCopy(fields()[11].schema(), other.validPageCnt);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.trafficSrcId)) {
        this.trafficSrcId = data().deepCopy(fields()[12].schema(), other.trafficSrcId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.exInternalIp)) {
        this.exInternalIp = data().deepCopy(fields()[13].schema(), other.exInternalIp);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.homepageCnt)) {
        this.homepageCnt = data().deepCopy(fields()[14].schema(), other.homepageCnt);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.signinPageCnt)) {
        this.signinPageCnt = data().deepCopy(fields()[15].schema(), other.signinPageCnt);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.cobrand)) {
        this.cobrand = data().deepCopy(fields()[16].schema(), other.cobrand);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[17].schema(), other.startTimestamp);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.endTimestamp)) {
        this.endTimestamp = data().deepCopy(fields()[18].schema(), other.endTimestamp);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.agentCnt)) {
        this.agentCnt = data().deepCopy(fields()[19].schema(), other.agentCnt);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.firstAppId)) {
        this.firstAppId = data().deepCopy(fields()[20].schema(), other.firstAppId);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.bidBinConfirmFlag)) {
        this.bidBinConfirmFlag = data().deepCopy(fields()[21].schema(), other.bidBinConfirmFlag);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.clientIp)) {
        this.clientIp = data().deepCopy(fields()[22].schema(), other.clientIp);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.absStartTimestamp)) {
        this.absStartTimestamp = data().deepCopy(fields()[23].schema(), other.absStartTimestamp);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.absEndTimestamp)) {
        this.absEndTimestamp = data().deepCopy(fields()[24].schema(), other.absEndTimestamp);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.familyViCnt)) {
        this.familyViCnt = data().deepCopy(fields()[25].schema(), other.familyViCnt);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.agentString)) {
        this.agentString = data().deepCopy(fields()[26].schema(), other.agentString);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.botFlagList)) {
        this.botFlagList = data().deepCopy(fields()[27].schema(), other.botFlagList);
        fieldSetFlags()[27] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing IntermediateSession instance
     *
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.sojourner.ubd.common.model.IntermediateSession other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.guid)) {
        this.guid = data().deepCopy(fields()[0].schema(), other.guid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.guid1)) {
        this.guid1 = data().deepCopy(fields()[1].schema(), other.guid1);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.guid2)) {
        this.guid2 = data().deepCopy(fields()[2].schema(), other.guid2);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.absEventCnt)) {
        this.absEventCnt = data().deepCopy(fields()[3].schema(), other.absEventCnt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.nonIframeRdtEventCnt)) {
        this.nonIframeRdtEventCnt = data()
            .deepCopy(fields()[4].schema(), other.nonIframeRdtEventCnt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.ip)) {
        this.ip = data().deepCopy(fields()[5].schema(), other.ip);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.userAgent)) {
        this.userAgent = data().deepCopy(fields()[6].schema(), other.userAgent);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.singleClickSessionFlag)) {
        this.singleClickSessionFlag = data()
            .deepCopy(fields()[7].schema(), other.singleClickSessionFlag);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.botFlag)) {
        this.botFlag = data().deepCopy(fields()[8].schema(), other.botFlag);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.firstCguid)) {
        this.firstCguid = data().deepCopy(fields()[9].schema(), other.firstCguid);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.firstUserId)) {
        this.firstUserId = data().deepCopy(fields()[10].schema(), other.firstUserId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.validPageCnt)) {
        this.validPageCnt = data().deepCopy(fields()[11].schema(), other.validPageCnt);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.trafficSrcId)) {
        this.trafficSrcId = data().deepCopy(fields()[12].schema(), other.trafficSrcId);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.exInternalIp)) {
        this.exInternalIp = data().deepCopy(fields()[13].schema(), other.exInternalIp);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.homepageCnt)) {
        this.homepageCnt = data().deepCopy(fields()[14].schema(), other.homepageCnt);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.signinPageCnt)) {
        this.signinPageCnt = data().deepCopy(fields()[15].schema(), other.signinPageCnt);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.cobrand)) {
        this.cobrand = data().deepCopy(fields()[16].schema(), other.cobrand);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.startTimestamp)) {
        this.startTimestamp = data().deepCopy(fields()[17].schema(), other.startTimestamp);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.endTimestamp)) {
        this.endTimestamp = data().deepCopy(fields()[18].schema(), other.endTimestamp);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.agentCnt)) {
        this.agentCnt = data().deepCopy(fields()[19].schema(), other.agentCnt);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.firstAppId)) {
        this.firstAppId = data().deepCopy(fields()[20].schema(), other.firstAppId);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.bidBinConfirmFlag)) {
        this.bidBinConfirmFlag = data().deepCopy(fields()[21].schema(), other.bidBinConfirmFlag);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.clientIp)) {
        this.clientIp = data().deepCopy(fields()[22].schema(), other.clientIp);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.absStartTimestamp)) {
        this.absStartTimestamp = data().deepCopy(fields()[23].schema(), other.absStartTimestamp);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.absEndTimestamp)) {
        this.absEndTimestamp = data().deepCopy(fields()[24].schema(), other.absEndTimestamp);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.familyViCnt)) {
        this.familyViCnt = data().deepCopy(fields()[25].schema(), other.familyViCnt);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.agentString)) {
        this.agentString = data().deepCopy(fields()[26].schema(), other.agentString);
        fieldSetFlags()[26] = true;
      }
      if (isValidValue(fields()[27], other.botFlagList)) {
        this.botFlagList = data().deepCopy(fields()[27].schema(), other.botFlagList);
        fieldSetFlags()[27] = true;
      }
    }

    /**
     * Gets the value of the 'guid' field. from ubisession guid
     *
     * @return The value.
     */
    public java.lang.String getGuid() {
      return guid;
    }

    /**
     * Sets the value of the 'guid' field. from ubisession guid
     *
     * @param value The value of 'guid'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setGuid(
        java.lang.String value) {
      validate(fields()[0], value);
      this.guid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'guid' field has been set. from ubisession guid
     *
     * @return True if the 'guid' field has been set, false otherwise.
     */
    public boolean hasGuid() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'guid' field. from ubisession guid
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearGuid() {
      guid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'guid1' field. from ubisession guid1
     *
     * @return The value.
     */
    public java.lang.Long getGuid1() {
      return guid1;
    }

    /**
     * Sets the value of the 'guid1' field. from ubisession guid1
     *
     * @param value The value of 'guid1'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setGuid1(
        java.lang.Long value) {
      validate(fields()[1], value);
      this.guid1 = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'guid1' field has been set. from ubisession guid1
     *
     * @return True if the 'guid1' field has been set, false otherwise.
     */
    public boolean hasGuid1() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'guid1' field. from ubisession guid1
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearGuid1() {
      guid1 = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'guid2' field. from ubisession guid2
     *
     * @return The value.
     */
    public java.lang.Long getGuid2() {
      return guid2;
    }

    /**
     * Sets the value of the 'guid2' field. from ubisession guid2
     *
     * @param value The value of 'guid2'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setGuid2(
        java.lang.Long value) {
      validate(fields()[2], value);
      this.guid2 = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'guid2' field has been set. from ubisession guid2
     *
     * @return True if the 'guid2' field has been set, false otherwise.
     */
    public boolean hasGuid2() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'guid2' field. from ubisession guid2
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearGuid2() {
      guid2 = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'absEventCnt' field. from ubisession absEventCnt
     *
     * @return The value.
     */
    public java.lang.Integer getAbsEventCnt() {
      return absEventCnt;
    }

    /**
     * Sets the value of the 'absEventCnt' field. from ubisession absEventCnt
     *
     * @param value The value of 'absEventCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setAbsEventCnt(
        java.lang.Integer value) {
      validate(fields()[3], value);
      this.absEventCnt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'absEventCnt' field has been set. from ubisession absEventCnt
     *
     * @return True if the 'absEventCnt' field has been set, false otherwise.
     */
    public boolean hasAbsEventCnt() {
      return fieldSetFlags()[3];
    }


    /**
     * Clears the value of the 'absEventCnt' field. from ubisession absEventCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearAbsEventCnt() {
      absEventCnt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'nonIframeRdtEventCnt' field. from ubisession nonIframeRdtEventCnt
     *
     * @return The value.
     */
    public java.lang.Integer getNonIframeRdtEventCnt() {
      return nonIframeRdtEventCnt;
    }

    /**
     * Sets the value of the 'nonIframeRdtEventCnt' field. from ubisession nonIframeRdtEventCnt
     *
     * @param value The value of 'nonIframeRdtEventCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setNonIframeRdtEventCnt(
        java.lang.Integer value) {
      validate(fields()[4], value);
      this.nonIframeRdtEventCnt = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'nonIframeRdtEventCnt' field has been set. from ubisession
     * nonIframeRdtEventCnt
     *
     * @return True if the 'nonIframeRdtEventCnt' field has been set, false otherwise.
     */
    public boolean hasNonIframeRdtEventCnt() {
      return fieldSetFlags()[4];
    }


    /**
     * Clears the value of the 'nonIframeRdtEventCnt' field. from ubisession nonIframeRdtEventCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder
    clearNonIframeRdtEventCnt() {
      nonIframeRdtEventCnt = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'ip' field. from ubisession ip
     *
     * @return The value.
     */
    public java.lang.String getIp() {
      return ip;
    }

    /**
     * Sets the value of the 'ip' field. from ubisession ip
     *
     * @param value The value of 'ip'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setIp(
        java.lang.String value) {
      validate(fields()[5], value);
      this.ip = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'ip' field has been set. from ubisession ip
     *
     * @return True if the 'ip' field has been set, false otherwise.
     */
    public boolean hasIp() {
      return fieldSetFlags()[5];
    }


    /**
     * Clears the value of the 'ip' field. from ubisession ip
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearIp() {
      ip = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
     * Gets the value of the 'userAgent' field. from ubisession userAgent
     *
     * @return The value.
     */
    public java.lang.String getUserAgent() {
      return userAgent;
    }

    /**
     * Sets the value of the 'userAgent' field. from ubisession userAgent
     *
     * @param value The value of 'userAgent'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setUserAgent(
        java.lang.String value) {
      validate(fields()[6], value);
      this.userAgent = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
     * Checks whether the 'userAgent' field has been set. from ubisession userAgent
     *
     * @return True if the 'userAgent' field has been set, false otherwise.
     */
    public boolean hasUserAgent() {
      return fieldSetFlags()[6];
    }


    /**
     * Clears the value of the 'userAgent' field. from ubisession userAgent
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearUserAgent() {
      userAgent = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
     * Gets the value of the 'singleClickSessionFlag' field. from ubisession singleClickSessionFlag
     *
     * @return The value.
     */
    public java.lang.Boolean getSingleClickSessionFlag() {
      return singleClickSessionFlag;
    }

    /**
     * Sets the value of the 'singleClickSessionFlag' field. from ubisession singleClickSessionFlag
     *
     * @param value The value of 'singleClickSessionFlag'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder
    setSingleClickSessionFlag(
        java.lang.Boolean value) {
      validate(fields()[7], value);
      this.singleClickSessionFlag = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
     * Checks whether the 'singleClickSessionFlag' field has been set. from ubisession
     * singleClickSessionFlag
     *
     * @return True if the 'singleClickSessionFlag' field has been set, false otherwise.
     */
    public boolean hasSingleClickSessionFlag() {
      return fieldSetFlags()[7];
    }


    /**
     * Clears the value of the 'singleClickSessionFlag' field. from ubisession
     * singleClickSessionFlag
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder
    clearSingleClickSessionFlag() {
      singleClickSessionFlag = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
     * Gets the value of the 'botFlag' field. from ubisession botFlag
     *
     * @return The value.
     */
    public java.lang.Integer getBotFlag() {
      return botFlag;
    }

    /**
     * Sets the value of the 'botFlag' field. from ubisession botFlag
     *
     * @param value The value of 'botFlag'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setBotFlag(
        java.lang.Integer value) {
      validate(fields()[8], value);
      this.botFlag = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
     * Checks whether the 'botFlag' field has been set. from ubisession botFlag
     *
     * @return True if the 'botFlag' field has been set, false otherwise.
     */
    public boolean hasBotFlag() {
      return fieldSetFlags()[8];
    }


    /**
     * Clears the value of the 'botFlag' field. from ubisession botFlag
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearBotFlag() {
      botFlag = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
     * Gets the value of the 'firstCguid' field. from ubisession firstCguid
     *
     * @return The value.
     */
    public java.lang.String getFirstCguid() {
      return firstCguid;
    }

    /**
     * Sets the value of the 'firstCguid' field. from ubisession firstCguid
     *
     * @param value The value of 'firstCguid'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setFirstCguid(
        java.lang.String value) {
      validate(fields()[9], value);
      this.firstCguid = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
     * Checks whether the 'firstCguid' field has been set. from ubisession firstCguid
     *
     * @return True if the 'firstCguid' field has been set, false otherwise.
     */
    public boolean hasFirstCguid() {
      return fieldSetFlags()[9];
    }


    /**
     * Clears the value of the 'firstCguid' field. from ubisession firstCguid
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearFirstCguid() {
      firstCguid = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
     * Gets the value of the 'firstUserId' field. from ubisession firstUserId
     *
     * @return The value.
     */
    public java.lang.String getFirstUserId() {
      return firstUserId;
    }

    /**
     * Sets the value of the 'firstUserId' field. from ubisession firstUserId
     *
     * @param value The value of 'firstUserId'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setFirstUserId(
        java.lang.String value) {
      validate(fields()[10], value);
      this.firstUserId = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
     * Checks whether the 'firstUserId' field has been set. from ubisession firstUserId
     *
     * @return True if the 'firstUserId' field has been set, false otherwise.
     */
    public boolean hasFirstUserId() {
      return fieldSetFlags()[10];
    }


    /**
     * Clears the value of the 'firstUserId' field. from ubisession firstUserId
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearFirstUserId() {
      firstUserId = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
     * Gets the value of the 'validPageCnt' field. from ubisession validPageCnt
     *
     * @return The value.
     */
    public java.lang.Integer getValidPageCnt() {
      return validPageCnt;
    }

    /**
     * Sets the value of the 'validPageCnt' field. from ubisession validPageCnt
     *
     * @param value The value of 'validPageCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setValidPageCnt(
        java.lang.Integer value) {
      validate(fields()[11], value);
      this.validPageCnt = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
     * Checks whether the 'validPageCnt' field has been set. from ubisession validPageCnt
     *
     * @return True if the 'validPageCnt' field has been set, false otherwise.
     */
    public boolean hasValidPageCnt() {
      return fieldSetFlags()[11];
    }


    /**
     * Clears the value of the 'validPageCnt' field. from ubisession validPageCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearValidPageCnt() {
      validPageCnt = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
     * Gets the value of the 'trafficSrcId' field. from ubisession trafficSrcId
     *
     * @return The value.
     */
    public java.lang.Integer getTrafficSrcId() {
      return trafficSrcId;
    }

    /**
     * Sets the value of the 'trafficSrcId' field. from ubisession trafficSrcId
     *
     * @param value The value of 'trafficSrcId'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setTrafficSrcId(
        java.lang.Integer value) {
      validate(fields()[12], value);
      this.trafficSrcId = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
     * Checks whether the 'trafficSrcId' field has been set. from ubisession trafficSrcId
     *
     * @return True if the 'trafficSrcId' field has been set, false otherwise.
     */
    public boolean hasTrafficSrcId() {
      return fieldSetFlags()[12];
    }


    /**
     * Clears the value of the 'trafficSrcId' field. from ubisession trafficSrcId
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearTrafficSrcId() {
      trafficSrcId = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
     * Gets the value of the 'exInternalIp' field. from ubisession exInternalIp
     *
     * @return The value.
     */
    public java.lang.String getExInternalIp() {
      return exInternalIp;
    }

    /**
     * Sets the value of the 'exInternalIp' field. from ubisession exInternalIp
     *
     * @param value The value of 'exInternalIp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setExInternalIp(
        java.lang.String value) {
      validate(fields()[13], value);
      this.exInternalIp = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
     * Checks whether the 'exInternalIp' field has been set. from ubisession exInternalIp
     *
     * @return True if the 'exInternalIp' field has been set, false otherwise.
     */
    public boolean hasExInternalIp() {
      return fieldSetFlags()[13];
    }


    /**
     * Clears the value of the 'exInternalIp' field. from ubisession exInternalIp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearExInternalIp() {
      exInternalIp = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
     * Gets the value of the 'homepageCnt' field. from ubisession homepageCnt
     *
     * @return The value.
     */
    public java.lang.Integer getHomepageCnt() {
      return homepageCnt;
    }

    /**
     * Sets the value of the 'homepageCnt' field. from ubisession homepageCnt
     *
     * @param value The value of 'homepageCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setHomepageCnt(
        java.lang.Integer value) {
      validate(fields()[14], value);
      this.homepageCnt = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
     * Checks whether the 'homepageCnt' field has been set. from ubisession homepageCnt
     *
     * @return True if the 'homepageCnt' field has been set, false otherwise.
     */
    public boolean hasHomepageCnt() {
      return fieldSetFlags()[14];
    }


    /**
     * Clears the value of the 'homepageCnt' field. from ubisession homepageCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearHomepageCnt() {
      homepageCnt = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
     * Gets the value of the 'signinPageCnt' field. fron ubisession signinPageCnt
     *
     * @return The value.
     */
    public java.lang.Integer getSigninPageCnt() {
      return signinPageCnt;
    }

    /**
     * Sets the value of the 'signinPageCnt' field. fron ubisession signinPageCnt
     *
     * @param value The value of 'signinPageCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setSigninPageCnt(
        java.lang.Integer value) {
      validate(fields()[15], value);
      this.signinPageCnt = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
     * Checks whether the 'signinPageCnt' field has been set. fron ubisession signinPageCnt
     *
     * @return True if the 'signinPageCnt' field has been set, false otherwise.
     */
    public boolean hasSigninPageCnt() {
      return fieldSetFlags()[15];
    }


    /**
     * Clears the value of the 'signinPageCnt' field. fron ubisession signinPageCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearSigninPageCnt() {
      signinPageCnt = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
     * Gets the value of the 'cobrand' field. from ubisession cobrand
     *
     * @return The value.
     */
    public java.lang.Integer getCobrand() {
      return cobrand;
    }

    /**
     * Sets the value of the 'cobrand' field. from ubisession cobrand
     *
     * @param value The value of 'cobrand'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setCobrand(
        java.lang.Integer value) {
      validate(fields()[16], value);
      this.cobrand = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
     * Checks whether the 'cobrand' field has been set. from ubisession cobrand
     *
     * @return True if the 'cobrand' field has been set, false otherwise.
     */
    public boolean hasCobrand() {
      return fieldSetFlags()[16];
    }


    /**
     * Clears the value of the 'cobrand' field. from ubisession cobrand
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearCobrand() {
      cobrand = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
     * Gets the value of the 'startTimestamp' field. from ubisession startTimestamp
     *
     * @return The value.
     */
    public java.lang.Long getStartTimestamp() {
      return startTimestamp;
    }

    /**
     * Sets the value of the 'startTimestamp' field. from ubisession startTimestamp
     *
     * @param value The value of 'startTimestamp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setStartTimestamp(
        java.lang.Long value) {
      validate(fields()[17], value);
      this.startTimestamp = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
     * Checks whether the 'startTimestamp' field has been set. from ubisession startTimestamp
     *
     * @return True if the 'startTimestamp' field has been set, false otherwise.
     */
    public boolean hasStartTimestamp() {
      return fieldSetFlags()[17];
    }


    /**
     * Clears the value of the 'startTimestamp' field. from ubisession startTimestamp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearStartTimestamp() {
      startTimestamp = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
     * Gets the value of the 'endTimestamp' field. from ubisession endTimestamp
     *
     * @return The value.
     */
    public java.lang.Long getEndTimestamp() {
      return endTimestamp;
    }

    /**
     * Sets the value of the 'endTimestamp' field. from ubisession endTimestamp
     *
     * @param value The value of 'endTimestamp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setEndTimestamp(
        java.lang.Long value) {
      validate(fields()[18], value);
      this.endTimestamp = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
     * Checks whether the 'endTimestamp' field has been set. from ubisession endTimestamp
     *
     * @return True if the 'endTimestamp' field has been set, false otherwise.
     */
    public boolean hasEndTimestamp() {
      return fieldSetFlags()[18];
    }


    /**
     * Clears the value of the 'endTimestamp' field. from ubisession endTimestamp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearEndTimestamp() {
      endTimestamp = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
     * Gets the value of the 'agentCnt' field. from ubisession agentCnt
     *
     * @return The value.
     */
    public java.lang.Integer getAgentCnt() {
      return agentCnt;
    }

    /**
     * Sets the value of the 'agentCnt' field. from ubisession agentCnt
     *
     * @param value The value of 'agentCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setAgentCnt(
        java.lang.Integer value) {
      validate(fields()[19], value);
      this.agentCnt = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
     * Checks whether the 'agentCnt' field has been set. from ubisession agentCnt
     *
     * @return True if the 'agentCnt' field has been set, false otherwise.
     */
    public boolean hasAgentCnt() {
      return fieldSetFlags()[19];
    }


    /**
     * Clears the value of the 'agentCnt' field. from ubisession agentCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearAgentCnt() {
      agentCnt = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
     * Gets the value of the 'firstAppId' field. from ubisession firstAppId
     *
     * @return The value.
     */
    public java.lang.Integer getFirstAppId() {
      return firstAppId;
    }

    /**
     * Sets the value of the 'firstAppId' field. from ubisession firstAppId
     *
     * @param value The value of 'firstAppId'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setFirstAppId(
        java.lang.Integer value) {
      validate(fields()[20], value);
      this.firstAppId = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
     * Checks whether the 'firstAppId' field has been set. from ubisession firstAppId
     *
     * @return True if the 'firstAppId' field has been set, false otherwise.
     */
    public boolean hasFirstAppId() {
      return fieldSetFlags()[20];
    }


    /**
     * Clears the value of the 'firstAppId' field. from ubisession firstAppId
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearFirstAppId() {
      firstAppId = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
     * Gets the value of the 'bidBinConfirmFlag' field. from ubisession bidBinConfirmFlag
     *
     * @return The value.
     */
    public java.lang.Boolean getBidBinConfirmFlag() {
      return bidBinConfirmFlag;
    }

    /**
     * Sets the value of the 'bidBinConfirmFlag' field. from ubisession bidBinConfirmFlag
     *
     * @param value The value of 'bidBinConfirmFlag'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setBidBinConfirmFlag(
        java.lang.Boolean value) {
      validate(fields()[21], value);
      this.bidBinConfirmFlag = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
     * Checks whether the 'bidBinConfirmFlag' field has been set. from ubisession bidBinConfirmFlag
     *
     * @return True if the 'bidBinConfirmFlag' field has been set, false otherwise.
     */
    public boolean hasBidBinConfirmFlag() {
      return fieldSetFlags()[21];
    }


    /**
     * Clears the value of the 'bidBinConfirmFlag' field. from ubisession bidBinConfirmFlag
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder
    clearBidBinConfirmFlag() {
      bidBinConfirmFlag = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
     * Gets the value of the 'clientIp' field. from ubisession clientIp
     *
     * @return The value.
     */
    public java.lang.String getClientIp() {
      return clientIp;
    }

    /**
     * Sets the value of the 'clientIp' field. from ubisession clientIp
     *
     * @param value The value of 'clientIp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setClientIp(
        java.lang.String value) {
      validate(fields()[22], value);
      this.clientIp = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
     * Checks whether the 'clientIp' field has been set. from ubisession clientIp
     *
     * @return True if the 'clientIp' field has been set, false otherwise.
     */
    public boolean hasClientIp() {
      return fieldSetFlags()[22];
    }


    /**
     * Clears the value of the 'clientIp' field. from ubisession clientIp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearClientIp() {
      clientIp = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
     * Gets the value of the 'absStartTimestamp' field. from ubisession absStartTimestamp
     *
     * @return The value.
     */
    public java.lang.Long getAbsStartTimestamp() {
      return absStartTimestamp;
    }

    /**
     * Sets the value of the 'absStartTimestamp' field. from ubisession absStartTimestamp
     *
     * @param value The value of 'absStartTimestamp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setAbsStartTimestamp(
        java.lang.Long value) {
      validate(fields()[23], value);
      this.absStartTimestamp = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
     * Checks whether the 'absStartTimestamp' field has been set. from ubisession absStartTimestamp
     *
     * @return True if the 'absStartTimestamp' field has been set, false otherwise.
     */
    public boolean hasAbsStartTimestamp() {
      return fieldSetFlags()[23];
    }


    /**
     * Clears the value of the 'absStartTimestamp' field. from ubisession absStartTimestamp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder
    clearAbsStartTimestamp() {
      absStartTimestamp = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
     * Gets the value of the 'absEndTimestamp' field. from ubisession absEndTimestamp
     *
     * @return The value.
     */
    public java.lang.Long getAbsEndTimestamp() {
      return absEndTimestamp;
    }

    /**
     * Sets the value of the 'absEndTimestamp' field. from ubisession absEndTimestamp
     *
     * @param value The value of 'absEndTimestamp'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setAbsEndTimestamp(
        java.lang.Long value) {
      validate(fields()[24], value);
      this.absEndTimestamp = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
     * Checks whether the 'absEndTimestamp' field has been set. from ubisession absEndTimestamp
     *
     * @return True if the 'absEndTimestamp' field has been set, false otherwise.
     */
    public boolean hasAbsEndTimestamp() {
      return fieldSetFlags()[24];
    }


    /**
     * Clears the value of the 'absEndTimestamp' field. from ubisession absEndTimestamp
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearAbsEndTimestamp() {
      absEndTimestamp = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
     * Gets the value of the 'familyViCnt' field. from ubisession familyViCnt
     *
     * @return The value.
     */
    public java.lang.Integer getFamilyViCnt() {
      return familyViCnt;
    }

    /**
     * Sets the value of the 'familyViCnt' field. from ubisession familyViCnt
     *
     * @param value The value of 'familyViCnt'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setFamilyViCnt(
        java.lang.Integer value) {
      validate(fields()[25], value);
      this.familyViCnt = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
     * Checks whether the 'familyViCnt' field has been set. from ubisession familyViCnt
     *
     * @return True if the 'familyViCnt' field has been set, false otherwise.
     */
    public boolean hasFamilyViCnt() {
      return fieldSetFlags()[25];
    }


    /**
     * Clears the value of the 'familyViCnt' field. from ubisession familyViCnt
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearFamilyViCnt() {
      familyViCnt = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
     * Gets the value of the 'agentString' field. from ubisession agentString
     *
     * @return The value.
     */
    public java.lang.String getAgentString() {
      return agentString;
    }

    /**
     * Sets the value of the 'agentString' field. from ubisession agentString
     *
     * @param value The value of 'agentString'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setAgentString(
        java.lang.String value) {
      validate(fields()[26], value);
      this.agentString = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
     * Checks whether the 'agentString' field has been set. from ubisession agentString
     *
     * @return True if the 'agentString' field has been set, false otherwise.
     */
    public boolean hasAgentString() {
      return fieldSetFlags()[26];
    }


    /**
     * Clears the value of the 'agentString' field. from ubisession agentString
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearAgentString() {
      agentString = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    /**
     * Gets the value of the 'botFlagList' field.
     *
     * @return The value.
     */
    public java.util.List<java.lang.Integer> getBotFlagList() {
      return botFlagList;
    }

    /**
     * Sets the value of the 'botFlagList' field.
     *
     * @param value The value of 'botFlagList'.
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder setBotFlagList(
        java.util.List<java.lang.Integer> value) {
      validate(fields()[27], value);
      this.botFlagList = value;
      fieldSetFlags()[27] = true;
      return this;
    }

    /**
     * Checks whether the 'botFlagList' field has been set.
     *
     * @return True if the 'botFlagList' field has been set, false otherwise.
     */
    public boolean hasBotFlagList() {
      return fieldSetFlags()[27];
    }


    /**
     * Clears the value of the 'botFlagList' field.
     *
     * @return This builder.
     */
    public com.ebay.sojourner.ubd.common.model.IntermediateSession.Builder clearBotFlagList() {
      botFlagList = null;
      fieldSetFlags()[27] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public IntermediateSession build() {
      try {
        IntermediateSession record = new IntermediateSession();
        record.guid = fieldSetFlags()[0] ? this.guid : (java.lang.String) defaultValue(fields()[0]);
        record.guid1 = fieldSetFlags()[1] ? this.guid1 : (java.lang.Long) defaultValue(fields()[1]);
        record.guid2 = fieldSetFlags()[2] ? this.guid2 : (java.lang.Long) defaultValue(fields()[2]);
        record.absEventCnt =
            fieldSetFlags()[3] ? this.absEventCnt : (java.lang.Integer) defaultValue(fields()[3]);
        record.nonIframeRdtEventCnt = fieldSetFlags()[4] ? this.nonIframeRdtEventCnt
            : (java.lang.Integer) defaultValue(fields()[4]);
        record.ip = fieldSetFlags()[5] ? this.ip : (java.lang.String) defaultValue(fields()[5]);
        record.userAgent =
            fieldSetFlags()[6] ? this.userAgent : (java.lang.String) defaultValue(fields()[6]);
        record.singleClickSessionFlag = fieldSetFlags()[7] ? this.singleClickSessionFlag
            : (java.lang.Boolean) defaultValue(fields()[7]);
        record.botFlag =
            fieldSetFlags()[8] ? this.botFlag : (java.lang.Integer) defaultValue(fields()[8]);
        record.firstCguid =
            fieldSetFlags()[9] ? this.firstCguid : (java.lang.String) defaultValue(fields()[9]);
        record.firstUserId =
            fieldSetFlags()[10] ? this.firstUserId : (java.lang.String) defaultValue(fields()[10]);
        record.validPageCnt = fieldSetFlags()[11] ? this.validPageCnt
            : (java.lang.Integer) defaultValue(fields()[11]);
        record.trafficSrcId = fieldSetFlags()[12] ? this.trafficSrcId
            : (java.lang.Integer) defaultValue(fields()[12]);
        record.exInternalIp =
            fieldSetFlags()[13] ? this.exInternalIp : (java.lang.String) defaultValue(fields()[13]);
        record.homepageCnt =
            fieldSetFlags()[14] ? this.homepageCnt : (java.lang.Integer) defaultValue(fields()[14]);
        record.signinPageCnt = fieldSetFlags()[15] ? this.signinPageCnt
            : (java.lang.Integer) defaultValue(fields()[15]);
        record.cobrand =
            fieldSetFlags()[16] ? this.cobrand : (java.lang.Integer) defaultValue(fields()[16]);
        record.startTimestamp =
            fieldSetFlags()[17] ? this.startTimestamp : (java.lang.Long) defaultValue(fields()[17]);
        record.endTimestamp =
            fieldSetFlags()[18] ? this.endTimestamp : (java.lang.Long) defaultValue(fields()[18]);
        record.agentCnt =
            fieldSetFlags()[19] ? this.agentCnt : (java.lang.Integer) defaultValue(fields()[19]);
        record.firstAppId =
            fieldSetFlags()[20] ? this.firstAppId : (java.lang.Integer) defaultValue(fields()[20]);
        record.bidBinConfirmFlag = fieldSetFlags()[21] ? this.bidBinConfirmFlag
            : (java.lang.Boolean) defaultValue(fields()[21]);
        record.clientIp =
            fieldSetFlags()[22] ? this.clientIp : (java.lang.String) defaultValue(fields()[22]);
        record.absStartTimestamp = fieldSetFlags()[23] ? this.absStartTimestamp
            : (java.lang.Long) defaultValue(fields()[23]);
        record.absEndTimestamp = fieldSetFlags()[24] ? this.absEndTimestamp
            : (java.lang.Long) defaultValue(fields()[24]);
        record.familyViCnt =
            fieldSetFlags()[25] ? this.familyViCnt : (java.lang.Integer) defaultValue(fields()[25]);
        record.agentString =
            fieldSetFlags()[26] ? this.agentString : (java.lang.String) defaultValue(fields()[26]);
        record.botFlagList = fieldSetFlags()[27] ? this.botFlagList
            : (java.util.List<java.lang.Integer>) defaultValue(fields()[27]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

}
