/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.sojourner.ubd.model;

import lombok.Data;

@Data
public class UbiEvent  {
  private String guid;
  private Long sessionSkey;
  private Integer seqNum;
  private Long sessionStartDt;
  private Long sojDataDt;
  private Integer clickId;
  private Integer siteId;
  private Integer version;
  private Integer pageId;
  private String pageName;
  private Long refererHash;
  private Long eventTimestamp;
  private String urlQueryString;
  private ClientData clientData;
  private String cookies;
  private String applicationPayload;
  private String webServer;
  private String referrer;
  private String userId;
  private Long itemId;
  private String flags;
  private Integer rdt;
  private Integer regu;
  private String sqr;
  private Integer staticPageType;
  private Integer reservedForFuture;
  private String eventAttr;
  private Long currentImprId;
  private Long sourceImprId;
  private Integer cobrand;
  private Integer iframe;
  private String agentInfo;
  private String forwardedFor;
  private String clientIP;
  private Integer bitVal;
  private Integer appId;
  private Long oldSessionSkey;
  private Integer hashCode;
  private Integer partialValidPage;


}
