flink:
  app:
    profile: test
    parallelism:
      metric-1st-aggr: 50
      metric-2nd-aggr: 1

    local-cache:
      queue-size: 1000
      flush-timeout: 5s
      output-partitions: 3

    sink:
      normal-metric:
        pronto-index-pattern: tdq.${flink.app.profile}.metric.normal.