flink:
  app:
    profile: prod
    sink:
      normal-metric:
        hdfs-path: hdfs://apollo-rno/user/b_bis/tdq/${flink.app.profile}/metric/normal
        pronto-index-pattern: tdq.${flink.app.profile}.metric.normal.
      latency-metric:
        hdfs-path: hdfs://apollo-rno/user/b_bis/tdq/${flink.app.profile}/metric/latency
        pronto-index-pattern: tdq.${flink.app.profile}.metric.latency.
      sample-log:
        pronto-index-pattern: tdq.${flink.app.profile}.log.sample.
      exception-log:
        pronto-index-pattern: tdq.${flink.app.profile}.log.exception.
mysql:
  jdbc:
    url: jdbc:mysql://mysqlidodb.db.stratus.ebay.com:3306/tdq?verifyServerCertificate=false&useSSL=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    u: uc4_user
    p: uc4_user