flink:
  app:
    name: TDQ-V2-pathfinder-pre-prod
    parallelism:
      default: 100
      source: 100
      metric-1st-aggr: 61
      metric-2nd-aggr: 2
    window:
      metric-1st-aggr: 1min
      supports: 1min,5min,10min,30min,1h,1d
    slot-sharing-group:
      source-event-lvs: tdq-lvs
      source-event-slc: tdq-slc
      source-event-rno: tdq-rno
    operator-name:
      source:
        rno: Pathfinder RNO Tdq Source
        lvs: Pathfinder LVS Tdq Source
        slc: Pathfinder SLC Tdq Source
    uid:
      source:
        rno: pathfinder-rno-tdq-source
        lvs: pathfinder-lvs-tdq-source
        slc: pathfinder-slc-tdq-source
    data-skew:
      is-filter: true
      guid-set: [ ]
      pageid-set: [ ]
    checkpoint:
      data-dir: /opt/tdq-pre-prd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    hot-deploy: false
    source:
      sample-fraction: 0
      from-timestamp: 0
      out-of-orderless-in-min: 3
      idle-source-timeout-in-min: 10
      pronto:
        index-pattern: tdq-metrics-pre-prod-
        latency-index-pattern: tdq-metrics-pre-prod-latency-
        scheme: https
        hostname: estdq-datalvs.vip.ebay.com
        port: 443
        username: _TDQ_SVC_USER
        password: "@BxHqFyz+Gzeq+2D"
    sink:
      types:
        - pronto
    advance:
      watermark:
        out-of-orderless: 5min
        idle-source-timeout: 10min
      local-combine:
        queue-size: 1000
        flush-timeout: 5000
mysql:
  jdbc:
    url: jdbc:mysql://mysql-master-svc-qa.ido-ns.svc.57.tess.io:3306/tdq?verifyServerCertificate=false&useSSL=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    user: dataops
    password: dataops#123

kafka:
  consumer:
    stream: behavior.pathfinder
    topic:
      - behavior.pathfinder.events.total
    group-id: tdq-v2
    bootstrap-servers:
      rno:
        - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
      lvs:
        - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092
    
    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 8MB, default value is 64KB
    receive-buffer: 8388608
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    auto-offset-reset: latest

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

rest-client:
  base-url: https://sojubdportalservice.vip.ebay.com
  username: soj-flink-app
  config:
    pull-interval: 30000
    env: prod
missing-cnt-exclude:
  u:
    - VI
ua-parser-env: prod