flink:
  app:
    name: TDQ-V2
    parallelism:
      default: 100
      source: 100
      metric-collector-by-window: 61
      metric-final-collector: 2
    window:
      supports: 10min,30min,1h,1d
      metric-collector-by-window: 5min
    slot-sharing-group:
      source-event-lvs: tdq-lvs
      source-event-slc: tdq-slc
      source-event-rno: tdq-rno
    operator-name:
      source:
        rno: Pathfinder RNO Tdq Source
        lvs: Pathfinder LVS Tdq Source
        slc: Pathfinder SLC Tdq Source
    uid:
      source:
        rno: pathfinder-rno-tdq-source
        lvs: pathfinder-lvs-tdq-source
        slc: pathfinder-slc-tdq-source
    data-skew:
      is-filter: true
      guid-set: [ ]
      pageid-set: [ ]
    checkpoint:
      data-dir: /opt/tdq/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    hot-deploy: false
    source:
      sample-fraction: 0.01
      from-timestamp: 0
      out-of-orderless-in-min: 3
      idle-source-timeout-in-min: 5
      pronto:
        index-pattern: tdq-metrics-test-
        latency-index-pattern: tdq-latency-metrics-test-
        scheme: https
        hostname: esgro-datarno.vip.ebay.com
        port: 443
        username: 4b538a6e7d4043b68d7da1f0c62ac304
        password: Te9xhZfDEkl6cEZ1jCx1akuxObSbUu75puv9mU6qNi7383nvKphEsDBzaHcGGUlr
    sink:
      types:
        - console
    advance:
      local-combine:
        queue-size: 1000
        flush-timeout: 5000

kafka:
  consumer:
    stream: behavior.pathfinder
    topic:
      - behavior.pathfinder.events.total
    group-id: tdq-v2
    bootstrap-servers:
      rno:
        - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
      lvs:
        - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092
    
    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 8MB, default value is 64KB
    receive-buffer: 8388608
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    auto-offset-reset: latest

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

rest-client:
  base-url: https://sojubdportalservice.vip.ebay.com
  username: soj-flink-app
  config:
    pull-interval: 30000
    env: prod
missing-cnt-exclude:
  u:
    - VI
ua-parser-env: prod