flink:
  app:
    parallelism:
      default: 125
      metric-1st-aggr: 200
      metric-2nd-aggr: 2

    window:
      metric-1st-aggr: 1min
      supports: 1min,5min

    checkpoint:
      data-dir: /opt/${flink.app.name}/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3

    local-cache:
      queue-size: 1000
      flush-timeout: 5s
      output-partitions: 61

pronto:
  scheme: https
  hostname: estdq-datalvs.vip.ebay.com
  port: 443
  api-key: 76361a1177564b72bdba1ddb23d17c58
  api-value: 1tIU7GQSADe4bCGGifWLfYYJSZGA8Szlc3ZWDMnd3gMhk43XPLUpw9Mv5viYQZ73

mysql:
  jdbc:
    url: jdbc:mysql://mysql-master-svc-qa.ido-ns.svc.57.tess.io:3306/tdq?verifyServerCertificate=false&useSSL=true&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    u: dataops
    p: dataops#123
